BEGIN TRY
    BEGIN TRANSACTION;
insert into Item(Nombre, Categoria, Descripcion, Unidad, Cantidad) values 
('Fondos', 'Fondos y financiamiento', 'Para financiamiento general', 'VE', 0),
('Cita para hemograma completo', 'Servicios médicos', 'Evaluación de componentes sanguíneos para diagnóstico general', 'MU', 0),
('Cita para química sanguínea', 'Servicios médicos', 'Análisis de glucosa urea  creatinina y otros parámetros', 'MU', 0),
('Cita para examen de glucosa', 'Servicios médicos', 'Medición del nivel de azúcar en sangre', 'MU', 0),
('Cita para perfil lipídico', 'Servicios médicos', 'Análisis de colesterol y triglicéridos', 'MU', 0),
('Cita para examen de orina', 'Servicios médicos', 'Evaluación física y química de la orina', 'MU', 0),
('Cita para examen de heces', 'Servicios médicos', 'Análisis para detección de parásitos o infecciones', 'MU', 0),
('Cita para prueba de embarazo', 'Servicios médicos', 'Detección de hormona hCG en sangre u orina', 'MU', 0),
('Cita para prueba de VIH', 'Servicios médicos', 'Detección de anticuerpos del virus VIH', 'MU', 0),
('Cita para prueba de sífilis', 'Servicios médicos', 'Examen serológico para detección de sífilis', 'MU', 0),
('Cita para grupo sanguíneo', 'Servicios médicos', 'Determinación del tipo y factor sanguíneo', 'MU', 0),
('Cita para examen de coagulación', 'Servicios médicos', 'Evaluación del tiempo de coagulación de la sangre', 'MU', 0),
('Cita para prueba de función hepática', 'Servicios médicos', 'Análisis del funcionamiento del hígado', 'MU', 0),
('Cita para prueba de función renal', 'Servicios médicos', 'Evaluación de la función de los riñones', 'MU', 0),
('Cita para examen de electrolitos', 'Servicios médicos', 'Medición de sodio  potasio y otros electrolitos', 'MU', 0),
('Cita para examen de tiroides', 'Servicios médicos', 'Evaluación hormonal de la glándula tiroides', 'MU', 0),
('Cita para radiografía de tórax', 'Servicios médicos', 'Imagen diagnóstica del área torácica', 'MU', 0),
('Cita para radiografía ósea', 'Servicios médicos', 'Estudio radiológico de huesos y articulaciones', 'MU', 0),
('Cita para ecografía abdominal', 'Servicios médicos', 'Estudio por ultrasonido de órganos abdominales', 'MU', 0),
('Cita para ecografía obstétrica', 'Servicios médicos', 'Evaluación del desarrollo fetal mediante ultrasonido', 'MU', 0),
('Cita para ecografía pélvica', 'Servicios médicos', 'Estudio de órganos reproductivos internos', 'MU', 0),
('Cita para mamografía', 'Servicios médicos', 'Examen radiológico para detección temprana de cáncer de mama', 'MU', 0),
('Cita para tomografía computarizada', 'Servicios médicos', 'Estudio de imágenes en cortes transversales del cuerpo', 'MU', 0),
('Cita para resonancia magnética', 'Servicios médicos', 'Estudio avanzado de imágenes por campos magnéticos', 'MU', 0),
('Cita para electrocardiograma', 'Servicios médicos', 'Registro de la actividad eléctrica del corazón', 'MU', 0),
('Cita para ecocardiograma', 'Servicios médicos', 'Evaluación del corazón mediante ultrasonido', 'MU', 0),
('Cita para prueba de esfuerzo', 'Servicios médicos', 'Evaluación cardíaca durante actividad física', 'MU', 0),
('Cita para espirometría', 'Servicios médicos', 'Evaluación de la función pulmonar', 'MU', 0),
('Cita para endoscopia digestiva', 'Servicios médicos', 'Exploración visual del tracto digestivo superior', 'MU', 0),
('Cita para colonoscopia', 'Servicios médicos', 'Exploración visual del colon y recto', 'MU', 0),
('Cita para densitometría ósea', 'Servicios médicos', 'Medición de la densidad mineral ósea', 'MU', 0),
('ACETAMINOFEN 500 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('ACETAMINOFEN 120 mg','Medicamentos','Forma farmaceútica: JBE','EU',0),
('ACETAMINOFEN 5 ml','Medicamentos','Forma farmaceútica: JBE','EU',0),
('ACETAMINOFEN 100 mg','Medicamentos','Forma farmaceútica: SOL GTS','EU',0),
('ACETAMINOFEN 100ml','Medicamentos','Forma farmaceútica: SOL GTS','EU',0),
('ACETAMINOFEN/CAFEINA/ERGOTAMINA 1 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('ACETAMINOFEN/CAFEINA/ERGOTAMINA 40 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('ACETAMINOFEN/CAFEINA/ERGOTAMINA 450 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('ACETAMINOFEN/CODEINA 500 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('ACETAMINOFEN/CODEINA 25 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('ACETAZOLAMIDA 250 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('ACETIL CISTEINA (N-ACETIL CISTEINA) 20 %','Medicamentos','Forma farmaceútica: AMP','EU',0),
('ACICLOVIR 250 mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('ACICLOVIR 200mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('ACICLOVIR 5%','Medicamentos','Forma farmaceútica: CREMA','EU',0),
('ACICLOVIR 3%','Medicamentos','Forma farmaceútica: UNG','EU',0),
('ÁCIDO ACETILSALICÍLICO 100 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('ÁCIDO ACETILSALICÍLICO 500 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('ÁCIDO ASCÓRBICO 100 mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('ÁCIDO ASCÓRBICO  ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('ÁCIDO FÓLICO 5 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('ÁCIDO FÓLICO 10 mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('ÁCIDO FÓLICO 10 ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('ACIDO TRANEXAMICO 0,5 g','Medicamentos','Forma farmaceútica: AMP','EU',0),
('ACIDO TRANEXAMICO 5 ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('ACIDO VALPROICO 500 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('ACIDO VALPROICO 260 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('ACIDO VALPROICO 250 mg','Medicamentos','Forma farmaceútica: JBE','EU',0),
('ACIDO VALPROICO  5 ml','Medicamentos','Forma farmaceútica: JBE','EU',0),
('ACTINOMICINA D 0,5 mg','Medicamentos','Forma farmaceútica: FCO VIAL','EU',0),
('ADRENALINA 1 mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('ADRENALINA 1 ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('AGUA ESTERIL PARA IRRIGACION 1000 ML','Medicamentos','Forma farmaceútica: VIAL','EU',0),
('AGUA PARA INYECCIÓN 2 ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('ALBENDAZOL 200 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('ALBENDAZOL 400mg','Medicamentos','Forma farmaceútica: SUSP','EU',0),
('ALBENDAZOL 10 ml','Medicamentos','Forma farmaceútica: SUSP','EU',0),
('ALBUMINA HUMANA 25 %','Medicamentos','Forma farmaceútica: AMP','EU',0),
('ALENDRONATO SODICO 70 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('ALENDRONATO SODICO 10 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('ALFA METIL DOPA 250 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('ALFA METIL DOPA 500 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('ALOPURINOL 100 mg','Medicamentos','Forma farmaceútica: TAB','EU',0),
('AMIKACINA 100 mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('AMIKACINA 500 mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('AMINOACIDOS 8,5 %','Medicamentos','Forma farmaceútica: FCO VIAL','EU',0),
('AMINOFILINA 240 mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('AMINOFILINA 10ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('AMIODARONA 200 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('AMIODARONA 150 mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('AMIODARONA 3 ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('AMLODIPINA BESILATO 5 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('AMOXICILINA CLAVULANICO 250mg','Medicamentos','Forma farmaceútica: POL/SUSP','EU',0),
('AMOXICILINA CLAVULANICO 62,5 mg','Medicamentos','Forma farmaceútica: POL/SUSP','EU',0),
('AMOXICILINA CLAVULANICO 5 ml','Medicamentos','Forma farmaceútica: POL/SUSP','EU',0),
('AMOXICILINA CLAVULANICO 500 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('AMOXICILINA CLAVULANICO 125 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('AMPICILINA 500 mg','Medicamentos','Forma farmaceútica: CAP','EU',0),
('AMPICILINA 1 g','Medicamentos','Forma farmaceútica: FCO VIAL','EU',0),
('AMPICILINA 250 mg','Medicamentos','Forma farmaceútica: SUSP','EU',0),
('AMPICILINA 5 ml','Medicamentos','Forma farmaceútica: SUSP','EU',0),
('AMPICILINA+SULBACTAM 1 g','Medicamentos','Forma farmaceútica: FCO VIAL','EU',0),
('AMPICILINA+SULBACTAM 500 mg','Medicamentos','Forma farmaceútica: FCO VIAL','EU',0),
('AMPRENAVIR 150 mg','Medicamentos','Forma farmaceútica: CAP','EU',0),
('AMPRENAVIR 15 mg','Medicamentos','Forma farmaceútica: SOL ORAL','EU',0),
('AMPRENAVIR 15 ml','Medicamentos','Forma farmaceútica: SOL ORAL','EU',0),
('ANFOTERICINA B 50 mg','Medicamentos','Forma farmaceútica: FCO VIAL','EU',0),
('ANTIMONIATO DE MEGLUMINA (N-METIL-GLUCAMINA) 1500 mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('ANTIMONIATO DE MEGLUMINA (N-METIL-GLUCAMINA) 5 ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('ANTITOXINA TETANICA 500 UI','Medicamentos','Forma farmaceútica: AMP','EU',0),
('ARTEMETERO 80 mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('ARTESUNATO 100 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('ASPARAGINASA (E. Coli) 10000UI','Medicamentos','Forma farmaceútica: FCO VIAL','EU',0),
('ATENOLOL 50 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('ATENOLOL 5 mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('ATENOLOL 10 ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('ATENOLOL 100 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('ATROPINA SULFATO 0,5 mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('ATROPINA SULFATO 0,5ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('AZATIOPRINA 50 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('AZITROMICINA 500 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('AZITROMICINA 200 mg','Medicamentos','Forma farmaceútica: SUSP','EU',0),
('AZITROMICINA 5 ml','Medicamentos','Forma farmaceútica: SUSP','EU',0),
('AZTREONAM 1 g','Medicamentos','Forma farmaceútica: FCO VIAL','EU',0),
('AZUL DE METILENO 1 %','Medicamentos','Forma farmaceútica: SOL','EU',0),
('BACITRACINA 500 UI','Medicamentos','Forma farmaceútica: UNG','EU',0),
('BACITRACINA 500g','Medicamentos','Forma farmaceútica: UNG','EU',0),
('BECLOMETASONA DIPROPIONATO 250 mcg','Medicamentos','Forma farmaceútica: INH-AER','EU',0),
('BECLOMETASONA DIPROPIONATO 250INH','Medicamentos','Forma farmaceútica: INH-AER','EU',0),
('BENZNIDAZOL 100 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('BENZOATO DE BENCILO 25%','Medicamentos','Forma farmaceútica: LCN','EU',0),
('BETAMETASONA VALERATO 0,1 %','Medicamentos','Forma farmaceútica: CREM','EU',0),
('BICARBONATO DE SODIO 5 %','Medicamentos','Forma farmaceútica: FCO','EU',0),
('BIPERIDENO CLORHIDRATO 2 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('BIPERIDENO LACTATO 5 mg','Medicamentos','Forma farmaceútica: SOL','EU',0),
('BIPERIDENO LACTATO  ml','Medicamentos','Forma farmaceútica: SOL','EU',0),
('BLEOMICINA 15 mg','Medicamentos','Forma farmaceútica: FCO VIAL','EU',0),
('BROMAZEPAM 3 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('BROMOCRIPTINA 2,5 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('BROMURO DE IPRATROPIO+FENOTEROL 0,25','Medicamentos','Forma farmaceútica: SOL NEB.','EU',0),
('BROMURO DE IPRATROPIO+FENOTEROL 0,50 mg','Medicamentos','Forma farmaceútica: SOL NEB.','EU',0),
('BUDESONIDA 0,25 mg','Medicamentos','Forma farmaceútica: SUSP/NEB','EU',0),
('BUDESONIDA 0,2ml','Medicamentos','Forma farmaceútica: SUSP/NEB','EU',0),
('BUPIVACAINA 0,50 %','Medicamentos','Forma farmaceútica: AMP','EU',0),
('BUSPIRONA 10 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('BUSPIRONA 5 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('BUSULFANO 2 mg','Medicamentos','Forma farmaceútica: COMP REC','EU',0),
('CABERGOLINA 0,5 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('CALAMINA 8 %','Medicamentos','Forma farmaceútica: LCN','EU',0),
('CARBAMAZEPINA 200 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('CARBAMAZEPINA 100 mg','Medicamentos','Forma farmaceútica: SUSP','EU',0),
('CARBAMAZEPINA 5 ml','Medicamentos','Forma farmaceútica: SUSP','EU',0),
('CARBON ACTIVADO ','Medicamentos','Forma farmaceútica: POL','EU',0),
('CARBONATO DE LITIO 300 mg','Medicamentos','Forma farmaceútica: CAP','EU',0),
('CARBOPLATINO 50 mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('CARBOPLATINO 150 mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('CARBOPLATINO 450 mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('CEFALEXINA 500 mg','Medicamentos','Forma farmaceútica: CAP','EU',0),
('CEFALEXINA 250 mg','Medicamentos','Forma farmaceútica: SUSP','EU',0),
('CEFALEXINA 5 ml','Medicamentos','Forma farmaceútica: SUSP','EU',0),
('CEFALOTINA 1 g','Medicamentos','Forma farmaceútica: FCO VIAL','EU',0),
('CEFEPIME 1 g','Medicamentos','Forma farmaceútica: FCO VIAL','EU',0),
('CEFOPERAZONA SULBACTAM 1g ','Medicamentos','Forma farmaceútica: FCO VIAL','EU',0),
('CEFOPERAZONA SULBACTAM 500 mg','Medicamentos','Forma farmaceútica: FCO VIAL','EU',0),
('CEFOTAXIMA 1 g','Medicamentos','Forma farmaceútica: FCO VIAL','EU',0),
('CEFOTAXIMA 0,5 g','Medicamentos','Forma farmaceútica: FCO VIAL','EU',0),
('CEFTAZIDIMA 1 g','Medicamentos','Forma farmaceútica: FCO VIAL','EU',0),
('CEFTAZIDIMA 0,5 g','Medicamentos','Forma farmaceútica: FCO VIAL','EU',0),
('CEFTRIAXONA 1 g','Medicamentos','Forma farmaceútica: FCO VIAL','EU',0),
('CEFTRIAXONA 0,5 g','Medicamentos','Forma farmaceútica: FCO VIAL','EU',0),
('CIANOCOBALAMINA 5 MG (VITA. B-12) 5 mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('CIANOCOBALAMINA 5 MG (VITA. B-12) 2 ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('CICLOFOSFAMIDA 50 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('CICLOFOSFAMIDA 200 mg','Medicamentos','Forma farmaceútica: FCO VIAL','EU',0),
('CICLOFOSFAMIDA 500 mg','Medicamentos','Forma farmaceútica: FCO VIAL','EU',0),
('CICLOFOSFAMIDA 1 g','Medicamentos','Forma farmaceútica: FCO VIAL','EU',0),
('CICLOSPORINA 50 mg','Medicamentos','Forma farmaceútica: CAP','EU',0),
('CICLOSPORINA 100 mg','Medicamentos','Forma farmaceútica: CAP','EU',0),
('CICLOSPORINA 25 mg','Medicamentos','Forma farmaceútica: CAP','EU',0),
('CICLOSPORINA 100 ml','Medicamentos','Forma farmaceútica: SOL ORAL','EU',0),
('CIPROFLOXACINA 500mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('CIPROFLOXACINA 200 mg','Medicamentos','Forma farmaceútica: FCO VIAL','EU',0),
('CIPROFLOXACINA 50 ml','Medicamentos','Forma farmaceútica: FCO VIAL','EU',0),
('CIPROFLOXACINA 100 mg','Medicamentos','Forma farmaceútica: FCO VIAL','EU',0),
('CIPROFLOXACINA  10 ml','Medicamentos','Forma farmaceútica: FCO VIAL','EU',0),
('CIPROFLOXACINA oftálmica 3,5 mg','Medicamentos','Forma farmaceútica: SOL GTS','EU',0),
('CISPLATINO 10 mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('CISPLATINO 10 ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('CISPLATINO 50 mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('CISPLATINO  50 ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('CISPLATINO 100 mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('CISPLATINO  100 ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('CITARABINA (CITOSINA ARABINOSA) 50 mg','Medicamentos','Forma farmaceútica: FCO VIAL','EU',0),
('CITARABINA (CITOSINA ARABINOSA) 100 mg','Medicamentos','Forma farmaceútica: FCO VIAL','EU',0),
('CITARABINA (CITOSINA ARABINOSA) 500 mg','Medicamentos','Forma farmaceútica: FCO VIAL','EU',0),
('CITARABINA (CITOSINA ARABINOSA) 1 g','Medicamentos','Forma farmaceútica: FCO VIAL','EU',0),
('CITARABINA (CITOSINA ARABINOSA) 2 g','Medicamentos','Forma farmaceútica: FCO VIAL','EU',0),
('CITRATO DE CALCIO (CITRATO TRICALCICO) 950 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('CLINDAMICINA 600 mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('CLINDAMICINA 300 mg','Medicamentos','Forma farmaceútica: CAP','EU',0),
('CLINDAMICINA 900 mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('CLINDAMICINA 150 mg','Medicamentos','Forma farmaceútica: CAP','EU',0),
('CLOFAZIMINA 100 mg','Medicamentos','Forma farmaceútica: CAP','EU',0),
('CLONIDINA 0,15 mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('CLONIDINA  ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('CLORAMFENICOL 1 g','Medicamentos','Forma farmaceútica: FCO VIAL','EU',0),
('CLORFENIRAMINA 10 mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('CLORFENIRAMINA  ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('CLORFENIRAMINA 4 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('CLORFENIRAMINA 2,5 mg','Medicamentos','Forma farmaceútica: JBE','EU',0),
('CLORFENIRAMINA 5 ml','Medicamentos','Forma farmaceútica: JBE','EU',0),
('CLOROQUINA (CLOROQUINA BASE) 200 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('CLOROQUINA (CLOROQUINA BASE) 150 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('CLOROQUINA (CLOROQUINA BASE) 50 mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('CLOROQUINA (CLOROQUINA BASE) 5 ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('CLOROQUINA (CLOROQUINA CLORHIDRATO) 100 mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('CLOROQUINA (CLOROQUINA CLORHIDRATO)  ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('CLORPROMAZINA 100 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('CLORPROMAZINA 50 mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('CLORPROMAZINA 2 ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('CLORURO DE POTASIO 1 meq','Medicamentos','Forma farmaceútica: FCO VIAL','EU',0),
('CLORURO DE POTASIO  ml','Medicamentos','Forma farmaceútica: FCO VIAL','EU',0),
('CLORURO DE POTASIO 20 meq','Medicamentos','Forma farmaceútica: AMP','EU',0),
('CLORURO DE POTASIO  10 ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('CLORURO DE SODIO 0,90 %','Medicamentos','Forma farmaceútica: SOL','EU',0),
('CLORURO DE SODIO 0,45 %','Medicamentos','Forma farmaceútica: SOL','EU',0),
('CLORURO DE SODIO 0,30 %','Medicamentos','Forma farmaceútica: SOL','EU',0),
('CLORURO DE SODIO 20 %','Medicamentos','Forma farmaceútica: SOL','EU',0),
('CLORURO DE SODIO/GLUCOSA 0,45','Medicamentos','Forma farmaceútica: SOL','EU',0),
('CLORURO DE SODIO/GLUCOSA  5 %','Medicamentos','Forma farmaceútica: SOL','EU',0),
('CLORURO DE SODIO/GLUCOSA 0.30','Medicamentos','Forma farmaceútica: SOL','EU',0),
('CLOTRIMAZOL 1 %','Medicamentos','Forma farmaceútica: CREM','EU',0),
('CLOTRIMAZOL 0,5 g','Medicamentos','Forma farmaceútica: OVU','EU',0),
('CODEINA 250 mg','Medicamentos','Forma farmaceútica: JBE','EU',0),
('CODEINA 100 ml','Medicamentos','Forma farmaceútica: JBE','EU',0),
('COLCHICINA 500 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('CROTAMITON 10%','Medicamentos','Forma farmaceútica: LCN','EU',0),
('CROTAMITON 10 %','Medicamentos','Forma farmaceútica: CREMA','EU',0),
('DACARBAZINA 100 mg','Medicamentos','Forma farmaceútica: FCO VIAL','EU',0),
('DACARBAZINA 200 mg','Medicamentos','Forma farmaceútica: FCO VIAL','EU',0),
('DACARBAZINA 500 mg','Medicamentos','Forma farmaceútica: FCO VIAL','EU',0),
('DANAZOL 100 mg','Medicamentos','Forma farmaceútica: CAP','EU',0),
('DANAZOL 200 mg','Medicamentos','Forma farmaceútica: CAP','EU',0),
('DAPSONA 100 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('DAPSONA 50 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('DAUNORUBICINA 20 mg','Medicamentos','Forma farmaceútica: FCO VIAL','EU',0),
('DEFEROXAMINA 500 mg','Medicamentos','Forma farmaceútica: FCO VIAL','EU',0),
('DELAVIRDINA 100 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('DESMOPRESINA ACETATO 4 mcg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('DESMOPRESINA ACETATO 4 ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('DESONIDA 0.10%','Medicamentos','Forma farmaceútica: CREM','EU',0),
('DEXAMETASONA 0,1%','Medicamentos','Forma farmaceútica: SOL TOPICA','EU',0),
('DEXAMETASONA 4 mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('DEXAMETASONA 4 ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('DEXAMETASONA 0,5 mg','Medicamentos','Forma farmaceútica: ELIX','EU',0),
('DEXAMETASONA 0,5ml','Medicamentos','Forma farmaceútica: ELIX','EU',0),
('DEXAMETASONA 0.05%','Medicamentos','Forma farmaceútica: UNG','EU',0),
('DEXTRANO 70 6.00%','Medicamentos','Forma farmaceútica: SOL','EU',0),
('DEXRAZOXANE 500 mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('DEXTROMETORFANO 15 mg','Medicamentos','Forma farmaceútica: JBE','EU',0),
('DEXTROMETORFANO 5ml','Medicamentos','Forma farmaceútica: JBE','EU',0),
('DEXTROSA (GLUCOSA) 5.00%','Medicamentos','Forma farmaceútica: SOL','EU',0),
('DEXTROSA (GLUCOSA) 10.00%','Medicamentos','Forma farmaceútica: SOL','EU',0),
('DEXTROSA (GLUCOSA) 50.00%','Medicamentos','Forma farmaceútica: SOL','EU',0),
('DIATRIZOATO DE MEGLUMINA 60%','Medicamentos','Forma farmaceútica: FCO VIAL','EU',0),
('DIAZEPAM 5 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('DIAZEPAM 10 mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('DIAZEPAM 2ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('DICLOFENACO SODICO 75 mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('DICLOFENACO SODICO 3 ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('DICLOFENACO SODICO 1mg','Medicamentos','Forma farmaceútica: SOL','EU',0),
('DICLOFENACO SODICO ml','Medicamentos','Forma farmaceútica: SOL','EU',0),
('DIDANOSINA 400mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('DIDANOSINA 100mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('DIGOXINA 0.25 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('DIGOXINA 0,6mg','Medicamentos','Forma farmaceútica: SOL/GTS','EU',0),
('DIGOXINA 0,6ml','Medicamentos','Forma farmaceútica: SOL/GTS','EU',0),
('DIGOXINA 0,2mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('DIGOXINA 2ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('DIMERCAPROL 100mg','Medicamentos','Forma farmaceútica: SOL','EU',0),
('DIPIRONA 500mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('DIPIRONA 500ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('DOBUTAMINA 250mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('DOBUTAMINA 5ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('DOPAMINA 250mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('DOPAMINA 5ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('DOXICICLINA 100 mg','Medicamentos','Forma farmaceútica: CAP','EU',0),
('DOXORUBICINA 100 mg','Medicamentos','Forma farmaceútica: FCO VIAL','EU',0),
('DOXORUBICINA 50 mg','Medicamentos','Forma farmaceútica: FCO VIAL','EU',0),
('DOXORUBICINA 10 mg','Medicamentos','Forma farmaceútica: FCO VIAL','EU',0),
('DOXORUBICINA LIPOSOMAL 20 mg','Medicamentos','Forma farmaceútica: FCO VIAL','EU',0),
('EDETATO SÓDICO CÁLCICO 1g','Medicamentos','Forma farmaceútica: SOL','EU',0),
('EFAVIRENZ 400mg','Medicamentos','Forma farmaceútica: COMP o CAP','EU',0),
('EMULSIONES GRASAS (LÍPIDOS) 20%','Medicamentos','Forma farmaceútica: FCO VIAL','EU',0),
('ENALAPRIL 5 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('ENALAPRIL 10 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('ENFLURANO 100%','Medicamentos','Forma farmaceútica: FCO/VIAL','EU',0),
('ENOXAPARINA SÓDICA 60mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('ERITROMICINA ESTOLATO 500 mg','Medicamentos','Forma farmaceútica: TAB','EU',0),
('ERITROMICINA ESTOLATO 250mg','Medicamentos','Forma farmaceútica: SUSP','EU',0),
('ERITROPOYETINA 1000 UI','Medicamentos','Forma farmaceútica: FCO/VIAL','EU',0),
('ERITROPOYETINA 2000 UI','Medicamentos','Forma farmaceútica: FCO/VIAL','EU',0),
('ERITROPOYETINA 4000 UI','Medicamentos','Forma farmaceútica: FCO/VIAL','EU',0),
('ESPIRONOLACTONA 25 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('ESPIRONOLACTONA 100 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('ESTREPTOMICINA 1g','Medicamentos','Forma farmaceútica: FCO/VIAL','EU',0),
('ESTREPTOQUINASA 1.500.000 UI','Medicamentos','Forma farmaceútica: FCO/VIAL','EU',0),
('ESTRÓGENOS CONJUGADOS 0,625 mg','Medicamentos','Forma farmaceútica: GRAGEA','EU',0),
('ETAMBUTOL 400 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('ETAMBUTOL 125 mg','Medicamentos','Forma farmaceútica: JBE','EU',0),
('ETANOL (ALCOHOL ETILICO) 70 %','Medicamentos','Forma farmaceútica: SOL','EU',0),
('ETOPOSIDO 100mg ','Medicamentos','Forma farmaceútica: AMP','EU',0),
('ETOPOSIDO  5ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('ETOPOSIDO 100 mg','Medicamentos','Forma farmaceútica: CAP','EU',0),
('ETOPOSIDO 50 mg','Medicamentos','Forma farmaceútica: CAP','EU',0),
('FACTOR ESTIMULANTE DE GRANULOCITOS (G-CSF) (FILGRASTIN) 300 mcg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('FACTOR ESTIMULANTE DE GRANULOCITOS (G-CSF) (FILGRASTIN) 480 mcg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('FACTOR ESTIMULANTE DE GRANULOCITOS Y MACROFAGOS (GM-CSF) (MOLGRAMOSTIN) 400 mcg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('FACTOR ESTIMULANTE DE GRANULOCITOS Y MACROFAGOS (GM-CSF) (MOLGRAMOSTIN) 300 mcg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('FACTOR ESTIMULANTE DE GRANULOCITOS Y MACROFAGOS (GM-CSF) (MOLGRAMOSTIN) 150 mcg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('FACTOR IX DE LA CUAGULACIÓN 500 UI','Medicamentos','Forma farmaceútica: FCO/VIAL','EU',0),
('FACTOR VIII DE LA CUAGULACIÓN 25 UI','Medicamentos','Forma farmaceútica: FCO/VIAL','EU',0),
('FACTOR VIII DE LA CUAGULACIÓN 25 ml','Medicamentos','Forma farmaceútica: FCO/VIAL','EU',0),
('FENITOINA 30 mg','Medicamentos','Forma farmaceútica: SUSP','EU',0),
('FENITOINA 4ml','Medicamentos','Forma farmaceútica: SUSP','EU',0),
('FENITOINA 100 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('FENITOINA 2ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('FENOBARBITAL 100 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('FENOBARBITAL 50mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('FENOBARBITAL 400mg ','Medicamentos','Forma farmaceútica: ELIX','EU',0),
('FENOBARBITAL  100ml','Medicamentos','Forma farmaceútica: ELIX','EU',0),
('FENOBARBITAL 200mg ','Medicamentos','Forma farmaceútica: AMP','EU',0),
('FENOBARBITAL  ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('FENOTEROL 0,5 mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('FENOTEROL  10 ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('FENTANILO 0,05 mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('FENTANILO 0,0ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('FENTANILO 10 mg','Medicamentos','Forma farmaceútica: PARCHE','EU',0),
('FENTANILO 5 mg','Medicamentos','Forma farmaceútica: PARCHE','EU',0),
('FENTOLAMINA 10 mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('FENTOLAMINA 10 ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('FISOSTIGMINA 2 mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('FISOSTIGMINA 2ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('FITOMENADIONA (VITAMINA K) 10 mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('FITOMENADIONA (VITAMINA K) 10 ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('FLUCONAZOL 150 mg','Medicamentos','Forma farmaceútica: CAP','EU',0),
('FLUCONAZOL 50 mg','Medicamentos','Forma farmaceútica: CAP','EU',0),
('FLUCONAZOL 2 mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('FLUCONAZOL 2 ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('FLUMAZENIL 0,5 mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('FLUMAZENIL 5ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('5-FLUOROURACILO 50 mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('5-FLUOROURACILO 50 ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('FLUOXETINA 20mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('FLUTAMIDA 250 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('FOLINATO DE CALCIO 15 mg','Medicamentos','Forma farmaceútica: TAB','EU',0),
('FOLINATO DE CALCIO (LEUCOVORINA CALCICA) 50 mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('FOSFATO MONOBÁSICO DE POTASIO 10%','Medicamentos','Forma farmaceútica: SOL','EU',0),
('FOSFOLIPIDO DE PULMON BOVINO 100 mg','Medicamentos','Forma farmaceútica: FCO/VIAL','EU',0),
('FOSFOLIPIDO DE PULMON BOVINO 4ml','Medicamentos','Forma farmaceútica: FCO/VIAL','EU',0),
('FUROSEMIDA 20mg ','Medicamentos','Forma farmaceútica: AMP','EU',0),
('FUROSEMIDA  2ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('FUROSEMIDA 40 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('GABAPENTINA 300 mg','Medicamentos','Forma farmaceútica: TAB','EU',0),
('GANCICLOVIR 250 mg','Medicamentos','Forma farmaceútica: CAP','EU',0),
('GANCICLOVIR 500 mg','Medicamentos','Forma farmaceútica: FCO/VIAL','EU',0),
('GANCICLOVIR 10 ml','Medicamentos','Forma farmaceútica: FCO/VIAL','EU',0),
('GEMCITABINA 200 mg','Medicamentos','Forma farmaceútica: FCO/VIAL','EU',0),
('GEMFIBROZILO 600 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('GENTAMICINA 40 mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('GENTAMICINA 40 ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('GENTAMICINA (OFTALMICA) 3mg','Medicamentos','Forma farmaceútica: SOL','EU',0),
('GENTAMICINA (OFTALMICA) ml','Medicamentos','Forma farmaceútica: SOL','EU',0),
('GENTAMICINA (OFTALMICA) 0,10%','Medicamentos','Forma farmaceútica: UNG','EU',0),
('GENTAMICINA 10 mg','Medicamentos','Forma farmaceútica: SOL','EU',0),
('GENTAMICINA 10 ml','Medicamentos','Forma farmaceútica: SOL','EU',0),
('GLIBENCLAMIDA 5 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('GLICERINA 2,88 g','Medicamentos','Forma farmaceútica: SUP','EU',0),
('GLICERINA 1,68 g','Medicamentos','Forma farmaceútica: SUP','EU',0),
('GLUCONATO DE CALCIO 10%','Medicamentos','Forma farmaceútica: SOL','EU',0),
('HALOPERIDOL 5 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('HALOPERIDOL 2 mg','Medicamentos','Forma farmaceútica: SOL GTS','EU',0),
('HALOPERIDOL 2 ml','Medicamentos','Forma farmaceútica: SOL GTS','EU',0),
('HALOPERIDOL 5 ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('HEPARINA SODICA 5000 U','Medicamentos','Forma farmaceútica: AMP','EU',0),
('HEPARINA SODICA  ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('HIDROCLOROTIAZIDA 25 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('HIDROCORTISONA 100 mg ','Medicamentos','Forma farmaceútica: AMP','EU',0),
('HIDROCORTISONA  2ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('HIDRÓXIDO DE ALUMINIO Y MAGNESIO 200','Medicamentos','Forma farmaceútica: SUSP','EU',0),
('HIDRÓXIDO DE ALUMINIO Y MAGNESIO 200 mg','Medicamentos','Forma farmaceútica: SUSP','EU',0),
('HIDRÓXIDO DE ALUMINIO Y MAGNESIO 5 ml','Medicamentos','Forma farmaceútica: SUSP','EU',0),
('HIDROXIUREA 500 mg','Medicamentos','Forma farmaceútica: CAP','EU',0),
('IBUPROFENO 400 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('IBUPROFENO 100 mg','Medicamentos','Forma farmaceútica: SUSP','EU',0),
('IBUPROFENO 5ml','Medicamentos','Forma farmaceútica: SUSP','EU',0),
('IFOSFAMIDA 1 g','Medicamentos','Forma farmaceútica: FCO/VIAL','EU',0),
('IMIPENEM CILASTATINA SODICA 500 ','Medicamentos','Forma farmaceútica: FCO/VIAL','EU',0),
('IMIPENEM CILASTATINA SODICA  500 mg','Medicamentos','Forma farmaceútica: FCO/VIAL','EU',0),
('IMIPRAMINA 25 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('INDINAVIR 400 mg','Medicamentos','Forma farmaceútica: COMP o CAP','EU',0),
('INDOMETACINA 50 mg','Medicamentos','Forma farmaceútica: CAP','EU',0),
('INDOMETACINA 25 mg','Medicamentos','Forma farmaceútica: CAP','EU',0),
('INMUNOGLOBULINA ANTI-D (Rh) (INMUNOGLOBULINA Rho (D) HUMANA) 300 mcg','Medicamentos','Forma farmaceútica: FCO/VIAL','EU',0),
('INMUNOGLOBULINA HUMANA NORMAL 2500 mg','Medicamentos','Forma farmaceútica: FCO/VIAL','EU',0),
('INMUNOGLOBULINA HUMANA NORMAL 50 ml','Medicamentos','Forma farmaceútica: FCO/VIAL','EU',0),
('INMUNOGLOBULINA HUMANA NORMAL 500 mg','Medicamentos','Forma farmaceútica: FCO/VIAL','EU',0),
('INMUNOGLOBULINA HUMANA NORMAL 10ml','Medicamentos','Forma farmaceútica: FCO/VIAL','EU',0),
('INMUNOGLOBULINA HUMANA NORMAL 5%','Medicamentos','Forma farmaceútica: FCO/VIAL','EU',0),
('INSULINA DE ACCION INTERMEDIA (INSULINA N.P.H HUMANA RECOMBINANTE) 100 UI','Medicamentos','Forma farmaceútica: FCO/VIAL','EU',0),
('INSULINA DE ACCION INTERMEDIA (INSULINA N.P.H HUMANA RECOMBINANTE) 100ml','Medicamentos','Forma farmaceútica: FCO/VIAL','EU',0),
('INSULINA DE ACCION INTERMEDIA (INSULINA PREMEZCLA CRISTALINA / N.P.H HUMANA RECOMBINANTE (30/70)) 30','Medicamentos','Forma farmaceútica: FCO/VIAL','EU',0),
('INSULINA DE ACCION INTERMEDIA (INSULINA PREMEZCLA CRISTALINA / N.P.H HUMANA RECOMBINANTE (30/70)) 70 U.I','Medicamentos','Forma farmaceútica: FCO/VIAL','EU',0),
('INSULINA DE ACCION INTERMEDIA (INSULINA PREMEZCLA CRISTALINA / N.P.H HUMANA RECOMBINANTE (30/70)) 70 ml','Medicamentos','Forma farmaceútica: FCO/VIAL','EU',0),
('INSULINA DE ACCION RAPIDA ( INSULINA CRISTALINA HUMANA RECOMBINANTE ) 100 UI','Medicamentos','Forma farmaceútica: FCO/VIAL','EU',0),
('INSULINA DE ACCION RAPIDA ( INSULINA CRISTALINA HUMANA RECOMBINANTE ) 100ml','Medicamentos','Forma farmaceútica: FCO/VIAL','EU',0),
('INTERFERON ALFA 2 B 10 MUI','Medicamentos','Forma farmaceútica: AMP','EU',0),
('INTERFERON ALFA 2 B 5 MUI','Medicamentos','Forma farmaceútica: AMP','EU',0),
('INTERFERON ALFA 2 B 3 MUI','Medicamentos','Forma farmaceútica: AMP','EU',0),
('IODAMIDA (SAL MEGLUMINICA Y SODICA DE LA IODAMIDA) 80%','Medicamentos','Forma farmaceútica: SOL','EU',0),
('IODO POVIDONA (POLIVIDONA IODADA) 10%','Medicamentos','Forma farmaceútica: SOL','EU',0),
('IODO POVIDONA (POLIVIDONA IODADA) 8%','Medicamentos','Forma farmaceútica: SOL JAB','EU',0),
('IOPAMIDOL 0,612 g','Medicamentos','Forma farmaceútica: AMP','EU',0),
('IOPAMIDOL 0,6ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('ISOFLURANO 100%','Medicamentos','Forma farmaceútica: SOL','EU',0),
('ISONIACIDA 300 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('ISOSORBIDA DINITRATO 5 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('ISOSORBIDA DINITRATO 10 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('ISPAGHULA (PSYLLIUM) 70%','Medicamentos','Forma farmaceútica: POLVO','EU',0),
('IVERMECTINA 6 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('KETAMINA 50 mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('KETAMINA 50 ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('KETOCONAZOL 200 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('KETOPROFENO 100 mg ','Medicamentos','Forma farmaceútica: AMP','EU',0),
('KETOPROFENO  5 ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('KETOPROFENO  2ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('LACTULOSA 67,30g','Medicamentos','Forma farmaceútica: AMP','EU',0),
('LACTULOSA 100 ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('LAGRIMAS ARTIFICIALES ','Medicamentos','Forma farmaceútica: SOL','EU',0),
('LAMIVUDINA 150 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('LEVODOPA / CARBIDOPA 250','Medicamentos','Forma farmaceútica: COMP','EU',0),
('LEVODOPA / CARBIDOPA 25mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('LEVOFLOXACINA 500 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('LEVOFLOXACINA 5 mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('LEVOFLOXACINA 5 ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('LEVOMEPROMAZINA 25 mg ','Medicamentos','Forma farmaceútica: AMP','EU',0),
('LEVOMEPROMAZINA  ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('LEVOMEPROMAZINA 100 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('LEVONORGESTREL / ETINILESTRADIOL 0,15mg','Medicamentos','Forma farmaceútica: GRAG','EU',0),
('LEVONORGESTREL / ETINILESTRADIOL 0,03mg','Medicamentos','Forma farmaceútica: GRAG','EU',0),
('LEVONORGESTREL / ETINILESTRADIOL 0,25','Medicamentos','Forma farmaceútica: GRAG','EU',0),
('LEVONORGESTREL / ETINILESTRADIOL 0,05mg','Medicamentos','Forma farmaceútica: GRAG','EU',0),
('LEVOTIROXINA SODICA 0,1 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('LEVOTIROXINA SODICA 0,05 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('LIDOCAINA 1 %','Medicamentos','Forma farmaceútica: SOL','EU',0),
('LIDOCAINA 2 %','Medicamentos','Forma farmaceútica: SOL','EU',0),
('LIDOCAINA 5 %','Medicamentos','Forma farmaceútica: SOL','EU',0),
('LIDOCAINA 20 mg ','Medicamentos','Forma farmaceútica: SOL','EU',0),
('LIDOCAINA 5 ml','Medicamentos','Forma farmaceútica: SOL','EU',0),
('LIDOCAINA / EPINEFRINA 1 %','Medicamentos','Forma farmaceútica: AMP','EU',0),
('LINDANO 1%','Medicamentos','Forma farmaceútica: LCN CHAMPÚ','EU',0),
('LORATADINA 1 mg','Medicamentos','Forma farmaceútica: JBE','EU',0),
('LORATADINA 1 ml','Medicamentos','Forma farmaceútica: JBE','EU',0),
('LORATADINA 10 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('LOSARTÁN 50 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('MACROGOL 3350 (POLIETILÉN GLICOL 3350) 60g','Medicamentos','Forma farmaceútica: POL','EU',0),
('MACROGOL 3350 (POLIETILÉN GLICOL 3350) 60sobre','Medicamentos','Forma farmaceútica: POL','EU',0),
('MANITOL 10%','Medicamentos','Forma farmaceútica: SOL','EU',0),
('MANITOL 18%','Medicamentos','Forma farmaceútica: SOL','EU',0),
('MEDROXIPROGESTERONA ACETATO 2,5mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('MEDROXIPROGESTERONA ACETATO 500mg','Medicamentos','Forma farmaceútica: SUSP','EU',0),
('MEDROXIPROGESTERONA ACETATO 2,5ml','Medicamentos','Forma farmaceútica: SUSP','EU',0),
('MEFLOQUINA CLORHIDRATO 250mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('MELFALÁN 2 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('MEPERIDINA (PETIDINA) 100mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('MEPERIDINA (PETIDINA) 2ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('MERCAPTOPURINA 50 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('MESNA 600 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('MESNA 1g','Medicamentos','Forma farmaceútica: AMP','EU',0),
('MESNA 400 mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('METFORMINA 500 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('METFORMINA 850 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('METILERGOMETRINA 0,2mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('METILERGOMETRINA 0,2ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('METILERGOMETRINA 0,125mg','Medicamentos','Forma farmaceútica: GRAG','EU',0),
('METILFENIDATO 10 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('METIMAZOL 5mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('METOCLOPRAMIDA 2ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('METOCLOPRAMIDA 10 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('METOCLOPRAMIDA 5mg','Medicamentos','Forma farmaceútica: JBE','EU',0),
('METOCLOPRAMIDA 5ml','Medicamentos','Forma farmaceútica: JBE','EU',0),
('METOPROLOL 100mg','Medicamentos','Forma farmaceútica: GRAG','EU',0),
('METOTREXATO 1 g','Medicamentos','Forma farmaceútica: AMP','EU',0),
('METOTREXATO 500 mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('METOTREXATO 200mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('METOTREXATO 100mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('METOTREXATO 50 mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('METOTREXATO 5 mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('METRONIDAZOL 500 mg','Medicamentos','Forma farmaceútica: OVU','EU',0),
('METRONIDAZOL  100 ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('METRONIDAZOL 500 ml','Medicamentos','Forma farmaceútica: COMP','EU',0),
('METRONIDAZOL -BENZOIL 250 mg','Medicamentos','Forma farmaceútica: SUSP','EU',0),
('METRONIDAZOL -BENZOIL 5ml','Medicamentos','Forma farmaceútica: SUSP','EU',0),
('MEXILETINA 200mg','Medicamentos','Forma farmaceútica: CAP','EU',0),
('MICOFENOLATO MOFETIL 500mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('MICOFENOLATO MOFETIL 250mg','Medicamentos','Forma farmaceútica: CAP','EU',0),
('MIDAZOLAM 15mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('MIDAZOLAM 3ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('MORFINA 30 mg','Medicamentos','Forma farmaceútica: COMP LC','EU',0),
('MORFINA 15 mg','Medicamentos','Forma farmaceútica: COMP LC','EU',0),
('MORFINA CLORHIDRATO 5 mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('MORFINA CLORHIDRATO  ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('MOSTAZA NITROGENADA 10 mg','Medicamentos','Forma farmaceútica: FCO/VIAL','EU',0),
('NALOXONA 0,4 mg ','Medicamentos','Forma farmaceútica: AMP','EU',0),
('NALOXONA  ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('NELFINAVIR 250mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('NELFINAVIR 50mg','Medicamentos','Forma farmaceútica: FCO/VIAL','EU',0),
('NELFINAVIR 50g','Medicamentos','Forma farmaceútica: FCO/VIAL','EU',0),
('NEOSTIGMINA 0.5 mg ','Medicamentos','Forma farmaceútica: AMP','EU',0),
('NEOSTIGMINA  ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('NEVIRAPINA 200 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('NIFEDIPINO 10mg','Medicamentos','Forma farmaceútica: CAP','EU',0),
('NIFEDIPINO 20mg','Medicamentos','Forma farmaceútica: COMP LC','EU',0),
('NIMESULIDA 100 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('NIMODIPINA 30mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('NIMODIPINA 10mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('NIMODIPINA 50ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('NISTATINA 500.000 U','Medicamentos','Forma farmaceútica: GRAG','EU',0),
('NISTATINA 100.000 U','Medicamentos','Forma farmaceútica: SUSP GTS','EU',0),
('NISTATINA 100000 U','Medicamentos','Forma farmaceútica: OVU','EU',0),
('NITROFURANTOÍNA MACROCRISTALES 100mg','Medicamentos','Forma farmaceútica: CAP','EU',0),
('NITROGLICERINA 5 mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('NITROGLICERINA 5 ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('NITROPRUSIATO SÓDICO 50 mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('OBIDOXIMA 250 mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('OBIDOXIMA 5 ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('OLANZAPINA 10 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('OLANZAPINA 5 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('OMEPRAZOL 20 mg','Medicamentos','Forma farmaceútica: CAP','EU',0),
('ONDANSETRON 4mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('ONDANSETRON 8mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('ONDANSETRÓN 4 mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('ONDANSETRÓN 2 ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('OXACILINA 1000 mg','Medicamentos','Forma farmaceútica: FCO/VIAL','EU',0),
('OXACILINA 500 mg','Medicamentos','Forma farmaceútica: FCO/VIAL','EU',0),
('OXACILINA 250 mg','Medicamentos','Forma farmaceútica: FCO/VIAL','EU',0),
('OXICODONA 40 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('OXICODONA 20 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('OXIMETAZOLINA CLORHIDRATO 0.025%','Medicamentos','Forma farmaceútica: AMP','EU',0),
('OXITETRACICLINA 250 mg','Medicamentos','Forma farmaceútica: CAP','EU',0),
('OXITOCINA 10UI','Medicamentos','Forma farmaceútica: AMP','EU',0),
('OXITOCINA 10ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('PACLITAXEL CON FILTRO 300 mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('PENICILAMINA 250 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('PENICILINA G BENZATINICA 1200000 UI','Medicamentos','Forma farmaceútica: FCO/VIAL','EU',0),
('PENICILINA G (BENZATINICA/PROCAÍNICA/CRISTALINA) 6','Medicamentos','Forma farmaceútica: FCO/VIAL','EU',0),
('PENICILINA G (BENZATINICA/PROCAÍNICA/CRISTALINA) 3','Medicamentos','Forma farmaceútica: FCO/VIAL','EU',0),
('PENICLINA G CRISTALINA 1.000.000 UI','Medicamentos','Forma farmaceútica: FCO/VIAL','EU',0),
('PENICLINA G PROCAINICA 400,000 UI','Medicamentos','Forma farmaceútica: FCO/VIAL','EU',0),
('PENTOXIFILINA 300 mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('PENTOXIFILINA 15ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('PENTOXIFILINA 400 mg','Medicamentos','Forma farmaceútica: COMP LP','EU',0),
('PERÓXIDO DE BENZOILO 5%','Medicamentos','Forma farmaceútica: LCN','EU',0),
('PERÓXIDO DE BENZOILO 10%','Medicamentos','Forma farmaceútica: LCN','EU',0),
('PILOCARPINA 4%','Medicamentos','Forma farmaceútica: SOL','EU',0),
('PILOCARPINA 2%','Medicamentos','Forma farmaceútica: SOL','EU',0),
('PIPERAZINA 10g','Medicamentos','Forma farmaceútica: JBE','EU',0),
('PIPERAZINA 100ml','Medicamentos','Forma farmaceútica: JBE','EU',0),
('PIRAZINAMIDA 400 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('PRAZIQUANTEL 150 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('PRAZIQUANTEL 250 mg','Medicamentos','Forma farmaceútica: SUSP','EU',0),
('PREDNISOLONA 2%','Medicamentos','Forma farmaceútica: UNG','EU',0),
('PREDNISOLONA 500 mg','Medicamentos','Forma farmaceútica: FCO/VIAL','EU',0),
('PREDNISOLONA 1 mg','Medicamentos','Forma farmaceútica: SUSP GTS','EU',0),
('PREDNISOLONA 1 ml','Medicamentos','Forma farmaceútica: SUSP GTS','EU',0),
('PREDNISONA 50 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('PREDNISONA 5mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('PRIMAQUINA 15 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('PRIMAQUINA 5 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('PRIMETAMINA 25 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('PRIMETAMINA/SULFADOXINA 25 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('PRIMETAMINA/SULFADOXINA 500 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('PROCARBAZINA 50 mg','Medicamentos','Forma farmaceútica: CAP','EU',0),
('PROPILTIOURACILO 50 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('PROPOFOL 10 mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('PROPOFOL 10 ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('PROTAMINA 10 mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('PROTAMINA 10 ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('QUININA DICLORHIDRATO 300mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('QUININA DICLORHIDRATO 300ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('QUININA SULFATO 500 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('QUININA SULFATO 250 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('RANITIDINA 300 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('RANITIDINA 150 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('RANITIDINA 50mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('RANITIDINA 2ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('RIFAMPICINA 300 mg','Medicamentos','Forma farmaceútica: CAP','EU',0),
('RIFAMPICINA 100 mg','Medicamentos','Forma farmaceútica: JBE','EU',0),
('RIFAMPICINA 5 ml','Medicamentos','Forma farmaceútica: JBE','EU',0),
('RISPERIDONA 3 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('RISPERIDONA 1 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('RITONAVIR 100mg','Medicamentos','Forma farmaceútica: CAP','EU',0),
('RITONAVIR 80 mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('RITONAVIR 80 ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('RITONAVIR/LOPINAVIR 33mg','Medicamentos','Forma farmaceútica: CAP','EU',0),
('RITONAVIR/LOPINAVIR 133mg','Medicamentos','Forma farmaceútica: CAP','EU',0),
('RITONAVIR/LOPINAVIR 20 mg','Medicamentos','Forma farmaceútica: SOL','EU',0),
('RITONAVIR/LOPINAVIR 80 mg','Medicamentos','Forma farmaceútica: SOL','EU',0),
('RITONAVIR/LOPINAVIR 80 ml','Medicamentos','Forma farmaceútica: SOL','EU',0),
('SALBUTAMOL 100 mcg','Medicamentos','Forma farmaceútica: POL','EU',0),
('SALBUTAMOL 100inh','Medicamentos','Forma farmaceútica: POL','EU',0),
('SALES DE REHIDRATACIÓN ORAL (SRO) ','Medicamentos','Forma farmaceútica: POL','EU',0),
('SALMETEROL 25 mcg','Medicamentos','Forma farmaceútica: POL','EU',0),
('SALMETEROL 25 inh','Medicamentos','Forma farmaceútica: POL','EU',0),
('SAQUINAVIR 200 mg','Medicamentos','Forma farmaceútica: CAP','EU',0),
('SENOSIDOS A Y B 8,6 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('SIMVASTATINA 20 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('SIMVASTATINA 10 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('SOLUCION PARA HEMODIALISIS: GLUCOSA CON POTASIO ','Medicamentos','Forma farmaceútica: SOL','EU',0),
('SOLUCION PARA HEMODIALISIS: GLUCOSA SIN POTASIO ','Medicamentos','Forma farmaceútica: SOL','EU',0),
('SOLUCION PARA HEMODIALISIS: SIN GLUCOSA CON POTASIO ','Medicamentos','Forma farmaceútica: SOL','EU',0),
('SOLUCION PARA HEMODIALISIS: SIN GLUCOSA SIN POTASIO ','Medicamentos','Forma farmaceútica: SOL','EU',0),
('SOLUCION PARA NUTRICION PARENTERAL 20 %','Medicamentos','Forma farmaceútica: SOL','EU',0),
('SOLUCIONES ELECTROLÍTICAS (RINGERLACTATO) ','Medicamentos','Forma farmaceútica: SOL / 500 ml','EU',0),
('SOLUCIONES ELECTROLÍTICAS (RINGER) ','Medicamentos','Forma farmaceútica: SOL / 500 ml','EU',0),
('SOLUCIONES PARA DIÁLISIS PERITONEAL 1,5 %','Medicamentos','Forma farmaceútica: SOL','EU',0),
('SOLUCIONES PARA DIÁLISIS PERITONEAL 4,25 %','Medicamentos','Forma farmaceútica: SOL','EU',0),
('STAVUDINA 40 mg','Medicamentos','Forma farmaceútica: COMP o CAP','EU',0),
('SUCCINILCOLINA (SUXAMETONIO) 50mg ','Medicamentos','Forma farmaceútica: AMP','EU',0),
('SUCCINILCOLINA (SUXAMETONIO)  ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('SUCRALFATO 1g ','Medicamentos','Forma farmaceútica: SUSP','EU',0),
('SUCRALFATO  5 ml','Medicamentos','Forma farmaceútica: SUSP','EU',0),
('SUERO ANTIESCORPIÓNICO ','Medicamentos','Forma farmaceútica: FCO/VIAL','EU',0),
('SUERO ANTIOFÍDICO POLIVALENTE ','Medicamentos','Forma farmaceútica: FCO/VIAL','EU',0),
('SUERO ANTIRRÁBICO 150 U ','Medicamentos','Forma farmaceútica: POL / SOL','EU',0),
('SUERO ANTIRRÁBICO  ml','Medicamentos','Forma farmaceútica: POL / SOL','EU',0),
('SULFADIAZINA DE PLATA 1 %','Medicamentos','Forma farmaceútica: CREMA','EU',0),
('SULFAMETOXAZOL+TRIMETOPRIM 400 mg ','Medicamentos','Forma farmaceútica: SUSP','EU',0),
('SULFAMETOXAZOL+TRIMETOPRIM 80 mg','Medicamentos','Forma farmaceútica: SUSP','EU',0),
('SULFAMETOXAZOL+TRIMETOPRIM  5 ml','Medicamentos','Forma farmaceútica: SUSP','EU',0),
('SULFAMETOXIPIRIDAZINA 500 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('SULFASALAZINA 500 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('SULFATO DE MAGNESIO 6 %','Medicamentos','Forma farmaceútica: FCO/VIAL','EU',0),
('SULFATO DE MAGNESIO 25 g ','Medicamentos','Forma farmaceútica: POLVO','EU',0),
('SULFATO DE MAGNESIO  sobre','Medicamentos','Forma farmaceútica: POLVO','EU',0),
('SULFATO FERROSO (HIERRO ELEMENTAL) 300mg (60mg)','Medicamentos','Forma farmaceútica: COMP','EU',0),
('SULFATO FERROSO (HIERRO ELEMENTAL) 125 mg','Medicamentos','Forma farmaceútica: SOL GOT','EU',0),
('SULFATO FERROSO (HIERRO ELEMENTAL) 125ml (25 mg)','Medicamentos','Forma farmaceútica: SOL GOT','EU',0),
('SULFATO FERROSO (HIERRO ELEMENTAL) 150mg','Medicamentos','Forma farmaceútica: JBE','EU',0),
('SULFATO FERROSO (HIERRO ELEMENTAL) 5ml (30 mg)','Medicamentos','Forma farmaceútica: JBE','EU',0),
('TAMOXIFENO 20 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('TAMOXIFENO 10 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('TETRACAÍNA 0.50%','Medicamentos','Forma farmaceútica: SOL','EU',0),
('TIERRA DE FULLER 60 g','Medicamentos','Forma farmaceútica: POL','EU',0),
('TIMOLOL 0.50%','Medicamentos','Forma farmaceútica: SOL','EU',0),
('TIMOLOL 0.25%','Medicamentos','Forma farmaceútica: SOL','EU',0),
('TINIDAZOL 500 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('TINIDAZOL 200 mg ','Medicamentos','Forma farmaceútica: SUSP','EU',0),
('TINIDAZOL  ml','Medicamentos','Forma farmaceútica: SUSP','EU',0),
('TIOCOLCHICÓSIDO 4 mg ','Medicamentos','Forma farmaceútica: AMP','EU',0),
('TIOCOLCHICÓSIDO  2 ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('TIOPENTAL 0,5 g','Medicamentos','Forma farmaceútica: FCO/VIAL','EU',0),
('TIORIDAZINA 100 mg','Medicamentos','Forma farmaceútica: GRAG','EU',0),
('TIORIDAZINA 25 mg','Medicamentos','Forma farmaceútica: GRAG','EU',0),
('TOXOIDE TETÁNICO ','Medicamentos','Forma farmaceútica: AMP','EU',0),
('TRAMADOL 50 mg','Medicamentos','Forma farmaceútica: CAP','EU',0),
('TRAMADOL  ml','Medicamentos','Forma farmaceútica: SOL GTS','EU',0),
('TRAMADOL 100 mg','Medicamentos','Forma farmaceútica: SOL','EU',0),
('TRAMADOL 2 ml','Medicamentos','Forma farmaceútica: SOL','EU',0),
('TRIAMCINOLONA ACETONIDA 40 mg ','Medicamentos','Forma farmaceútica: FCO/VIAL','EU',0),
('TRIAMCINOLONA ACETONIDA  ml','Medicamentos','Forma farmaceútica: FCO/VIAL','EU',0),
('TRIFLUOPERAZINA 10 mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('TRIIODOTIRONINA 0,02 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('TRIIODOTIRONINA 0,025 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('TROPICAMIDA 1 %','Medicamentos','Forma farmaceútica: AMP','EU',0),
('VACUNA ANTITUBERCULOSA (BCG) ','Medicamentos','Forma farmaceútica: FCO/VIAL','EU',0),
('VACUNA CONTRA EL HAEMOPHILUS
INFLUENZAE TIPO B ','Medicamentos','Forma farmaceútica: AMP','EU',0),
('VACUNA CONTRA EL SARAMPION ','Medicamentos','Forma farmaceútica: FCO/VIAL','EU',0),
('VACUNA CONTRA EL SARAMPION, RUBÉOLA Y PAROTIDITIS ','Medicamentos','Forma farmaceútica: FCO/VIAL','EU',0),
('VACUNA CONTRA LA DIFTERIA, TOSFERINA Y TÉTANOS (DIFTERIA, PERTUSIS Y TÉTANOS) ','Medicamentos','Forma farmaceútica: FCO/VIAL','EU',0),
('VACUNA CONTRA LA FIEBRE AMARILLA (ANTIMARÍLICA) ','Medicamentos','Forma farmaceútica: FCO/VIAL','EU',0),
('VACUNA CONTRA LA HEPATITIS B (ANTIHEPATITIS B) 20ug','Medicamentos','Forma farmaceútica: FCO/VIAL','EU',0),
('VACUNA CONTRA LA HEPATITIS (ANTIHEPATITIS B) 20ml','Medicamentos','Forma farmaceútica: FCO/VIAL','EU',0),
('VACUNA CONTRA LA POLIOMIELITIS (ANTIPOLIO) ','Medicamentos','Forma farmaceútica: AMP','EU',0),
('VACUNA CONTRA LA RABIA (ANTIRRÁBICA) ','Medicamentos','Forma farmaceútica: FCO/VIAL','EU',0),
('VANCOMICINA 1 g','Medicamentos','Forma farmaceútica: FCO/VIAL','EU',0),
('VANCOMICINA 0,5 g','Medicamentos','Forma farmaceútica: FCO/VIAL','EU',0),
('VECURONIO BROMURO 4 mg','Medicamentos','Forma farmaceútica: FCO/VIAL','EU',0),
('VERAPAMILO 40 mg','Medicamentos','Forma farmaceútica: GRAG','EU',0),
('VERAPAMILO 5 mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('VERAPAMILO 2 ml','Medicamentos','Forma farmaceútica: AMP','EU',0),
('VERAPAMILO 80 mg','Medicamentos','Forma farmaceútica: GRAG','EU',0),
('VINBLASTINA 10 mg','Medicamentos','Forma farmaceútica: FCO/VIAL','EU',0),
('VINCRISTINA 1 mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('VINCRISTINA 2 mg','Medicamentos','Forma farmaceútica: AMP','EU',0),
('WARFARINA SÓDICA 1 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('WARFARINA SÓDICA 2 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('WARFARINA SÓDICA 5 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('ZALCITABINA 0,75 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('ZIDOVUDINA 100 mg','Medicamentos','Forma farmaceútica: CAP','EU',0),
('ZIDOVUDINA 10 mg','Medicamentos','Forma farmaceútica: JBE','EU',0),
('ZIDOVUDINA 10 ml','Medicamentos','Forma farmaceútica: JBE','EU',0),
('ZIDOVUDINA 200 mg','Medicamentos','Forma farmaceútica: SOL','EU',0),
('ZIDOVUDINA 5ml','Medicamentos','Forma farmaceútica: SOL','EU',0),
('ZIDOVUDINA/LAMIVUDINA 300 mg','Medicamentos','Forma farmaceútica: COMP','EU',0),
('Prótesis de pierna transtibial','Prótesis', 'Prótesis para reemplazo de extremidad inferior por debajo de la rodilla', 'EU', 0),
('Prótesis de pierna transfemoral','Prótesis', 'Prótesis para reemplazo de extremidad inferior por encima de la rodilla', 'EU', 0),
('Prótesis de brazo transradial','Prótesis', 'Prótesis para amputación de brazo por debajo del codo', 'EU', 0),
('Prótesis de brazo transhumeral','Prótesis', 'Prótesis para amputación de brazo por encima del codo', 'EU', 0),
('Prótesis de mano mecánica','Prótesis', 'Dispositivo protésico para reemplazo funcional de la mano', 'EU', 0),
('Prótesis de mano mioeléctrica','Prótesis', 'Prótesis controlada por impulsos musculares', 'EU', 0),
('Prótesis de dedo','Prótesis', 'Reemplazo protésico de uno o varios dedos de la mano', 'EU', 0),
('Prótesis parcial de pie','Prótesis', 'Prótesis para amputación parcial del pie', 'EU', 0),
('Prótesis de tobillo','Prótesis', 'Dispositivo protésico para articulación del tobillo', 'EU', 0),
('Prótesis de rodilla mecánica','Prótesis', 'Articulación protésica para reemplazo de rodilla', 'EU', 0),
('Prótesis de rodilla hidráulica','Prótesis', 'Rodilla protésica con control hidráulico', 'EU', 0),
('Prótesis de cadera','Prótesis', 'Implante protésico para reemplazo de la articulación de la cadera', 'EU', 0),
('Prótesis de hombro','Prótesis', 'Implante para sustitución de la articulación del hombro', 'EU', 0),
('Prótesis de codo','Prótesis', 'Implante protésico para reemplazo del codo', 'EU', 0),
('Prótesis de muñeca','Prótesis', 'Dispositivo protésico para articulación de la muñeca', 'EU', 0),
('Prótesis ocular','Prótesis', 'Ojo artificial para reemplazo estético y anatómico', 'EU', 0),
('Prótesis maxilofacial','Prótesis', 'Prótesis para reconstrucción facial y craneal', 'EU', 0),
('Prótesis dental completa','Prótesis', 'Reemplazo total de piezas dentales', 'EU', 0),
('Prótesis dental parcial','Prótesis', 'Reemplazo parcial de piezas dentales', 'EU', 0),
('Prótesis auditiva implantable','Prótesis', 'Implante para mejorar la audición', 'EU', 0),
('Prótesis coclear','Prótesis', 'Implante electrónico para sordera profunda', 'EU', 0),
('Prótesis de mama externa','Prótesis', 'Prótesis externa para reemplazo mamario', 'EU', 0),
('Prótesis mamaria interna','Prótesis', 'Implante quirúrgico para reconstrucción mamaria', 'EU', 0),
('Prótesis de pene','Prótesis', 'Implante para restaurar la función eréctil', 'EU', 0),
('Prótesis testicular','Prótesis', 'Implante para reemplazo testicular', 'EU', 0),
('Prótesis de válvula cardíaca','Prótesis', 'Dispositivo para reemplazo de válvula del corazón', 'EU', 0),
('Prótesis vascular','Prótesis', 'Conducto artificial para reemplazo de vasos sanguíneos', 'EU', 0),
('Prótesis traqueal','Prótesis', 'Implante para sustitución parcial de la tráquea', 'EU', 0),
('Prótesis laríngea','Prótesis', 'Dispositivo para restaurar funciones de la laringe', 'EU', 0),
('Prótesis nasal','Prótesis', 'Reemplazo protésico de estructura nasal', 'EU', 0),
('Prótesis auricular','Prótesis', 'Reemplazo protésico del pabellón auricular', 'EU', 0),
('Prótesis craneal','Prótesis', 'Implante para reconstrucción del cráneo', 'EU', 0),
('Prótesis vertebral','Prótesis', 'Implante para estabilización o reemplazo vertebral', 'EU', 0),
('Prótesis de disco intervertebral','Prótesis', 'Reemplazo artificial del disco vertebral', 'EU', 0),
('Prótesis de columna cervical','Prótesis', 'Implante para soporte de la columna cervical', 'EU', 0),
('Prótesis de tobillo total','Prótesis', 'Reemplazo completo de la articulación del tobillo', 'EU', 0),
('Prótesis de pie completa','Prótesis', 'Reemplazo total del pie amputado', 'EU', 0),
('Prótesis de falange','Prótesis', 'Implante para reemplazo de falange del dedo', 'EU', 0),
('Prótesis de menisco','Prótesis', 'Implante para sustitución del menisco dañado', 'EU', 0),
('Prótesis de ligamento cruzado','Prótesis', 'Implante para reemplazo de ligamento de rodilla', 'EU', 0),
('Prótesis de cartílago articular','Prótesis', 'Implante para restaurar cartílago dañado', 'EU', 0),
('Prótesis de clavícula','Prótesis', 'Implante para reconstrucción de la clavícula', 'EU', 0),
('Prótesis de escápula','Prótesis', 'Implante para reemplazo parcial de la escápula', 'EU', 0),
('Prótesis de mandíbula','Prótesis', 'Implante para reconstrucción mandibular', 'EU', 0),
('Prótesis de maxilar superior','Prótesis', 'Implante para reconstrucción del maxilar', 'EU', 0),
('Prótesis de costilla','Prótesis', 'Implante para reemplazo de costillas dañadas', 'EU', 0),
('Prótesis torácica','Prótesis', 'Implante para reconstrucción de pared torácica', 'EU', 0),
('Prótesis de esternón','Prótesis', 'Implante para sustitución del esternón', 'EU', 0),
('Prótesis de esfínter urinario','Prótesis', 'Dispositivo para control de incontinencia urinaria', 'EU', 0),
('Prótesis de esfínter anal','Prótesis', 'Implante para restaurar continencia anal', 'EU', 0),
('Prótesis gástrica','Prótesis', 'Implante para reconstrucción parcial del estómago', 'EU', 0),
('Prótesis esofágica','Prótesis', 'Implante para reemplazo del esófago', 'EU', 0),
('Prótesis intestinal','Prótesis', 'Dispositivo para sustitución de segmentos intestinales', 'EU', 0),
('Prótesis hepática','Prótesis', 'Dispositivo artificial de soporte hepático', 'EU', 0),
('Prótesis renal','Prótesis', 'Dispositivo de soporte o reemplazo de función renal', 'EU', 0),
('Prótesis pulmonar','Prótesis', 'Implante para soporte respiratorio artificial', 'EU', 0),
('Prótesis cardíaca total','Prótesis', 'Dispositivo para reemplazo total del corazón', 'EU', 0),
('Prótesis de bypass coronario','Prótesis', 'Conducto artificial para desvío coronario', 'EU', 0),
('Prótesis de válvula mitral','Prótesis', 'Implante para reemplazo de válvula mitral', 'EU', 0),
('Prótesis de válvula aórtica','Prótesis', 'Implante para reemplazo de válvula aórtica', 'EU', 0),
('Prótesis de válvula pulmonar','Prótesis', 'Implante para reemplazo de válvula pulmonar', 'EU', 0),
('Prótesis de válvula tricúspide','Prótesis', 'Implante para reemplazo de válvula tricúspide', 'EU', 0),
('Prótesis de tendón','Prótesis', 'Implante para reemplazo de tendones dañados', 'EU', 0),
('Prótesis de músculo','Prótesis', 'Implante para soporte o sustitución muscular', 'EU', 0),
('Prótesis facial total','Prótesis', 'Reemplazo protésico completo de estructuras faciales', 'EU', 0),
('Prótesis orbital','Prótesis', 'Implante para reconstrucción de la órbita ocular', 'EU', 0),
('Prótesis de paladar','Prótesis', 'Implante para restauración del paladar', 'EU', 0),
('Prótesis de lengua','Prótesis', 'Dispositivo para reconstrucción parcial de la lengua', 'EU', 0),
('Prótesis de lóbulo auricular','Prótesis', 'Reemplazo protésico del lóbulo de la oreja', 'EU', 0),
('Prótesis personalizada 3D','Prótesis', 'Prótesis médica diseñada mediante impresión 3D', 'EU', 0),
('Silla de ruedas manual estándar','Equipos de movilidad asistida', 'Silla de ruedas de propulsión manual para movilidad básica del paciente', 'EU', 0),
('Silla de ruedas plegable','Equipos de movilidad asistida', 'Silla de ruedas manual plegable para fácil transporte y almacenamiento', 'EU', 0),
('Silla de ruedas eléctrica','Equipos de movilidad asistida', 'Silla de ruedas motorizada para personas con movilidad reducida severa', 'EU', 0),
('Silla de ruedas reclinable','Equipos de movilidad asistida', 'Silla de ruedas con respaldo reclinable para mayor comodidad y soporte', 'EU', 0),
('Silla de ruedas bariátrica','Equipos de movilidad asistida', 'Silla de ruedas reforzada para usuarios con mayor peso corporal', 'EU', 0),
('Scooter eléctrico de movilidad','Equipos de movilidad asistida', 'Vehículo eléctrico de asistencia para desplazamientos cortos y medianos', 'EU', 0),
('Andador fijo','Equipos de movilidad asistida', 'Estructura de apoyo para asistencia en la marcha sin ruedas', 'EU', 0),
('Andador con ruedas','Equipos de movilidad asistida', 'Andador con ruedas frontales para facilitar el desplazamiento', 'EU', 0),
('Andador rollator','Equipos de movilidad asistida', 'Andador con cuatro ruedas  frenos y asiento integrado', 'EU', 0),
('Bastón simple','Equipos de movilidad asistida', 'Dispositivo de apoyo básico para mejorar la estabilidad al caminar', 'EU', 0),
('Bastón ajustable','Equipos de movilidad asistida', 'Bastón con altura regulable para adaptación al usuario', 'EU', 0),
('Bastón de cuatro puntos','Equipos de movilidad asistida', 'Bastón con base de cuatro apoyos para mayor estabilidad', 'EU', 0),
('Muletas axilares','Equipos de movilidad asistida', 'Dispositivos de apoyo que descargan peso de las extremidades inferiores', 'EU', 0),
('Muletas canadienses','Equipos de movilidad asistida', 'Muletas de antebrazo para apoyo y equilibrio en la marcha', 'EU', 0),
('Silla de transferencia','Equipos de movilidad asistida', 'Silla diseñada para traslados cortos dentro del hogar o institución', 'EU', 0),
('Grúa de traslado para pacientes','Equipos de movilidad asistida', 'Equipo mecánico para movilizar personas con movilidad muy limitada', 'EU', 0),
('Grúa eléctrica de movilidad','Equipos de movilidad asistida', 'Grúa motorizada para elevación y traslado seguro de pacientes', 'EU', 0),
('Tabla de transferencia','Equipos de movilidad asistida', 'Dispositivo plano para facilitar transferencias entre superficies', 'EU', 0),
('Caminador pediátrico','Equipos de movilidad asistida', 'Equipo de apoyo para movilidad asistida en niños', 'EU', 0),
('Silla de ruedas neurológica','Equipos de movilidad asistida', 'Silla de ruedas especializada para pacientes con condiciones neurológicas', 'EU', 0),
('Guantes estériles', 'Insumos quirúrgicos', 'Guantes de látex o nitrilo estériles para procedimientos quirúrgicos', 'EU', 0),
('Mascarillas quirúrgicas', 'Insumos quirúrgicos', 'Mascarillas desechables para uso en quirófano', 'EU', 0),
('Batas estériles', 'Insumos quirúrgicos', 'Batas protectoras estériles para cirujanos y personal médico', 'EU', 0),
('Campos quirúrgicos', 'Insumos quirúrgicos', 'Paños estériles para delimitar el área quirúrgica', 'EU', 0),
('Gasas estériles', 'Insumos quirúrgicos', 'Gasas para absorción y limpieza durante cirugía', 'EU', 0),
('Suturas absorbibles', 'Insumos quirúrgicos', 'Hilos de sutura que se degradan en el cuerpo', 'EU', 0),
('Suturas no absorbibles', 'Insumos quirúrgicos', 'Hilos de sutura permanentes para cierre de tejidos', 'EU', 0),
('Jeringas desechables', 'Insumos quirúrgicos', 'Jeringas estériles de diferentes calibres', 'EU', 0),
('Agujas hipodérmicas', 'Insumos quirúrgicos', 'Agujas estériles para administración de medicamentos', 'EU', 0),
('Catéteres intravenosos', 'Insumos quirúrgicos', 'Dispositivos para acceso venoso periférico', 'EU', 0),
('Solución salina estéril', 'Insumos quirúrgicos', 'Solución fisiológica para irrigación y limpieza', 'EU', 0),
('Antisépticos', 'Insumos quirúrgicos', 'Ejemplo: povidona yodada para desinfección de piel', 'EU', 0),
('Esparadrapo médico', 'Insumos quirúrgicos', 'Cinta adhesiva para fijación de gasas y dispositivos', 'EU', 0),
('Compresas quirúrgicas', 'Insumos quirúrgicos', 'Compresas estériles para absorción de fluidos', 'EU', 0),
('Drapes adhesivos', 'Insumos quirúrgicos', 'Cubiertas adhesivas para aislamiento del campo quirúrgico', 'EU', 0),
('Tubos de drenaje', 'Insumos quirúrgicos', 'Dispositivos para evacuación de fluidos postoperatorios', 'EU', 0),
('Instrumental básico', 'Insumos quirúrgicos', 'Bisturí, tijeras, pinzas y otros instrumentos esenciales', 'EU', 0),
('Electrocauterio desechable', 'Insumos quirúrgicos', 'Dispositivo para coagulación y corte de tejidos', 'EU', 0),
('Bolsas de recolección de fluidos', 'Insumos quirúrgicos', 'Bolsas estériles para drenajes quirúrgicos', 'EU', 0),
('Sondas vesicales', 'Insumos quirúrgicos', 'Catéteres para drenaje urinario', 'EU', 0),
('Arroz parbolizado', 'Alimentos', 'Arroz de larga duración con mayor resistencia al almacenamiento', 'EU', 0),
('Arroz partido', 'Alimentos', 'Arroz económico apto para consumo humano', 'EU', 0),
('Harina de arroz', 'Alimentos', 'Harina no perecedera para preparación de alimentos', 'EU', 0),
('Harina de avena', 'Alimentos', 'Harina nutritiva para preparación de bebidas y comidas', 'EU', 0),
('Harina de plátano', 'Alimentos', 'Harina seca obtenida del plátano', 'EU', 0),
('Pasta corta seca', 'Alimentos', 'Pasta alimenticia seca de fácil cocción', 'EU', 0),
('Pasta larga seca', 'Alimentos', 'Pasta seca tipo espagueti de larga duración', 'EU', 0),
('Sémola de trigo', 'Alimentos', 'Derivado del trigo para preparación de alimentos', 'EU', 0),
('Cereal fortificado', 'Alimentos', 'Cereal seco enriquecido con vitaminas y minerales', 'EU', 0),
('Mezcla para arepas', 'Alimentos', 'Producto seco listo para preparación de arepas', 'EU', 0),
('Caraotas blancas', 'Alimentos', 'Leguminosa seca de alto contenido proteico', 'EU', 0),
('Caraotas pintas', 'Alimentos', 'Leguminosa seca para consumo familiar', 'EU', 0),
('Frijoles blancos secos', 'Alimentos', 'Leguminosa seca de fácil almacenamiento', 'EU', 0),
('Quinchoncho seco', 'Alimentos', 'Leguminosa seca tradicional venezolana', 'EU', 0),
('Arvejas secas', 'Alimentos', 'Leguminosa seca para sopas y guisos', 'EU', 0),
('Lentejas partidas', 'Alimentos', 'Lentejas secas de cocción rápida', 'EU', 0),
('Garbanzos partidos', 'Alimentos', 'Leguminosa seca procesada para fácil cocción', 'EU', 0),
('Soya texturizada', 'Alimentos', 'Proteína vegetal deshidratada', 'EU', 0),
('Proteína vegetal seca', 'Alimentos', 'Sustituto cárnico de origen vegetal', 'EU', 0),
('Carne de soya', 'Alimentos', 'Producto vegetal seco rico en proteínas', 'EU', 0),
('Sardinas en salsa', 'Alimentos', 'Pescado enlatado listo para consumo', 'EU', 0),
('Atún en agua', 'Alimentos', 'Conserva de pescado sin aceite', 'EU', 0),
('Atún en aceite', 'Alimentos', 'Conserva de pescado en aceite vegetal', 'EU', 0),
('Mezcla para sopa deshidratada', 'Alimentos', 'Producto seco para preparación de sopas', 'EU', 0),
('Cubitos de caldo', 'Alimentos', 'Condimento concentrado para preparación de comidas', 'EU', 0),
('Salsa de tomate enlatada', 'Alimentos', 'Salsa procesada de larga duración', 'EU', 0),
('Puré de tomate', 'Alimentos', 'Derivado del tomate en presentación no perecedera', 'EU', 0),
('Mayonesa en sobre', 'Alimentos', 'Salsa emulsionada en presentación individual', 'EU', 0),
('Vinagre blanco', 'Alimentos', 'Condimento líquido de uso básico', 'EU', 0),
('Salsa inglesa', 'Alimentos', 'Condimento líquido para realzar sabores', 'EU', 0),
('Café en grano', 'Alimentos', 'Grano de café tostado para consumo', 'EU', 0),
('Café instantáneo', 'Alimentos', 'Café soluble de larga duración', 'EU', 0),
('Cacao en polvo', 'Alimentos', 'Derivado del cacao para preparación de bebidas', 'EU', 0),
('Chocolate de mesa', 'Alimentos', 'Producto sólido a base de cacao', 'EU', 0),
('Pan rallado', 'Alimentos', 'Producto seco derivado del pan', 'EU', 0),
('Galletas simples', 'Alimentos', 'Galletas secas de larga duración', 'EU', 0),
('Galletas saladas', 'Alimentos', 'Galletas secas para consumo básico', 'EU', 0),
('Azúcar en sobres', 'Alimentos', 'Azúcar empacada en porciones individuales', 'EU', 0),
('Sal en sobres', 'Alimentos', 'Sal comestible empacada individualmente', 'EU', 0),
('Mezcla para bebida fortificada', 'Alimentos', 'Producto en polvo enriquecido con vitaminas', 'EU', 0),
('Cuaderno rayado','Útiles escolares', 'Cuaderno para escritura con líneas horizontales', 'EU', 0),
('Cuaderno cuadriculado','Útiles escolares', 'Cuaderno con cuadrícula para matemáticas y cálculos', 'EU', 0),
('Cuaderno blanco','Útiles escolares', 'Cuaderno de hojas blancas para dibujo y escritura libre', 'EU', 0),
('Cuaderno de doble línea','Útiles escolares', 'Cuaderno para aprendizaje de escritura infantil', 'EU', 0),
('Libreta pequeña','Útiles escolares', 'Libreta portátil para anotaciones rápidas', 'EU', 0),
('Agenda escolar','Útiles escolares', 'Agenda para organización de tareas y actividades académicas', 'EU', 0),
('Lápiz grafito','Útiles escolares', 'Lápiz de escritura con mina de grafito', 'EU', 0),
('Lápiz de colores','Útiles escolares', 'Set de lápices para dibujo y coloreado', 'EU', 0),
('Sacapuntas','Útiles escolares', 'Herramienta para afilar lápices', 'EU', 0),
('Borrador','Útiles escolares', 'Goma para borrar trazos de lápiz', 'EU', 0),
('Regla plástica','Útiles escolares', 'Instrumento de medición lineal para uso escolar', 'EU', 0),
('Regla metálica','Útiles escolares', 'Regla resistente para mediciones precisas', 'EU', 0),
('Compás','Útiles escolares', 'Instrumento para trazar círculos y arcos', 'EU', 0),
('Transportador','Útiles escolares', 'Instrumento para medir ángulos', 'EU', 0),
('Tijeras escolares','Útiles escolares', 'Tijeras de seguridad para uso académico', 'EU', 0),
('Pegamento en barra','Útiles escolares', 'Adhesivo sólido para trabajos escolares', 'EU', 0),
('Pegamento líquido','Útiles escolares', 'Adhesivo líquido para papel y cartón', 'EU', 0),
('Resaltador','Útiles escolares', 'Marcador fluorescente para resaltar texto', 'EU', 0),
('Marcadores escolares','Útiles escolares', 'Marcadores de colores para escritura y dibujo', 'EU', 0),
('Bolígrafo azul','Útiles escolares', 'Bolígrafo de tinta azul para escritura diaria', 'EU', 0),
('Bolígrafo negro','Útiles escolares', 'Bolígrafo de tinta negra para documentos', 'EU', 0),
('Bolígrafo rojo','Útiles escolares', 'Bolígrafo de tinta roja para correcciones', 'EU', 0),
('Corrector líquido','Útiles escolares', 'Producto para corregir errores de escritura', 'EU', 0),
('Corrector en cinta','Útiles escolares', 'Cinta adhesiva para corrección de texto', 'EU', 0),
('Cartulina','Útiles escolares', 'Papel grueso para trabajos manuales', 'EU', 0),
('Papel bond','Útiles escolares', 'Papel blanco para impresión y escritura', 'EU', 0),
('Papel de construcción','Útiles escolares', 'Papel de colores para actividades creativas', 'EU', 0),
('Carpeta escolar','Útiles escolares', 'Carpeta para organizar documentos y tareas', 'EU', 0),
('Carpeta con ganchos','Útiles escolares', 'Carpeta para archivado de hojas perforadas', 'EU', 0),
('Archivador','Útiles escolares', 'Elemento para almacenamiento de documentos', 'EU', 0),
('Estuche escolar','Útiles escolares', 'Bolso pequeño para guardar útiles escolares', 'EU', 0),
('Mochila escolar','Útiles escolares', 'Bolso para transporte de materiales académicos', 'EU', 0),
('Calculadora básica','Útiles escolares', 'Dispositivo electrónico para cálculos matemáticos', 'EU', 0),
('Calculadora científica','Útiles escolares', 'Calculadora avanzada para operaciones complejas', 'EU', 0),
('Crayones','Útiles escolares', 'Barras de cera para colorear', 'EU', 0),
('Pinturas al frío','Útiles escolares', 'Pinturas escolares a base de agua', 'EU', 0),
('Pinceles','Útiles escolares', 'Herramientas para aplicar pintura', 'EU', 0),
('Block de dibujo','Útiles escolares', 'Conjunto de hojas para dibujo artístico', 'EU', 0),
('Block de papel milimetrado','Útiles escolares', 'Hojas con cuadrícula precisa para dibujo técnico', 'EU', 0),
('Forros plásticos','Útiles escolares', 'Cubiertas protectoras para cuadernos y libros', 'EU', 0)
COMMIT;
END TRY
BEGIN CATCH
    ROLLBACK;
    PRINT 'Error en la transacción: ' + CAST(ERROR_LINE() as Varchar(10))+ ' ' + ERROR_MESSAGE();
END CATCH;